### ISSUE TITLE
Workflows under approval settings

### ISSUE THREAD

**Issue by larshelge** [dhis2/settings-app#19]
The settings app will need to be modified to manage approval workflows. In the Web API I've defined a DataApprovalWorkflowController to extend the AbstractCrudController<DataApprovalWorkflow>. I believe this will give the settings app all the web API calls it needs.

I had coded the UI in the old settings screens before the settings app was introduced. Here are some screen shots from that code showing what is needed -- but feel free to improve the look and feel. :)

1. Under Approval Settings, there is an additional thing to manage: Approval Workflows. In the old UI, I had coded this as managing approval levels on one screen and approval workflows on another. On the "levels" screen there was a button to get you to the "workflows" screen, and on the "workflows" screen there was a button to get you back to the "level" screen, as below.

Feel free to improve on this. For example, maybe you can have the two checkboxes "Hide ..." and "Acceptance ...", followed by tabs that let you manage levels under one tab, and workflows under the other tab.

![1](https://cloud.githubusercontent.com/assets/908206/11680283/4fae22e4-9e57-11e5-8da3-285adf9e8a9b.png)

2. When managing workflows, the context menu should have Edit and Remove. I suggest that you show each workflow with three columns: Name, Frequency, and Approval levels. The Approval levels column shows all the approval levels that are associated with that workflow, separated by spaces, like the following:

![2](https://cloud.githubusercontent.com/assets/908206/11680290/5550cb02-9e57-11e5-8d34-a9e0796d52d5.png)

3. When adding or editing an approval level, the fields should be name, frequency (periodType), and then a list of approval levels. For each approval level, there is the option to include it in this workflow or not, such as follows. (IMHO, checkboxes would be better than two-option dropdowns.)

![3](https://cloud.githubusercontent.com/assets/908206/11680291/58dc9a62-9e57-11e5-8b40-4a77ff27c67b.png)

![4](https://cloud.githubusercontent.com/assets/908206/11680292/5ddea708-9e57-11e5-8ef7-f643fd625e0d.png)

Please let me know if you have any questions.

**Comment by nicolayr** [comment]
Done!
