### ISSUE TITLE
User settings and override

### ISSUE THREAD

**Issue by larshelge** [dhis2/settings-app#23]
Add system settings for the following user settings.

UI_LOCALE / "keyUiLocale" (under Appearance)
DB_LOCALE / "keyDbLocale" (under Appearance)
ANALYSIS_DISPLAY_PROPERTY "keyAnalysisDisplayProperty" (under Appearance)
MESSAGE_EMAIL_NOTIFICATION "keyMessageEmailNotification" (under Messaging)
MESSAGE_SMS_NOTIFICATION "keyMessageSmsNotification" (under Messaging)

Add a new system setting page / menu item "Messaging".

https://play.dhis2.org/dev/dhis-web-commons-about/userSettings.action

Add visual indicators for these system settings which can be overridden by user settings. If overridden indicate the current user setting value.

**Comment by nicolayr** [comment]
User settings keys:
http://bazaar.launchpad.net/~dhis2-devs-core/dhis2/trunk/view/head:/dhis-2/dhis-api/src/main/java/org/hisp/dhis/user/UserSettingKey.java
