### ISSUE TITLE
Remove orgunit level from max offline levels

### ISSUE THREAD

**Issue by Markionium** [dhis2/settings-app#3]
As per @mortenoh 

Small issue though, you shouldn't have org unit level name in the offline org unit dropdown.. its relative to current users org unit.. so level 3 doesn't always mean level 3.. it just means maximum levels to offline in idb cache

<img width="480" alt="screen shot 2015-10-16 at 10 09 54" src="https://cloud.githubusercontent.com/assets/2134901/10541113/a46f1572-740e-11e5-8102-d6da4fb8c976.png">

**Comment by nicolayr** [comment]
Fixed in 97930c8737e588d0a79e34dd75a7c33f30bbf1d4
