### ISSUE TITLE
Add support for deep linking

### ISSUE THREAD

**Issue by nicolayr** [dhis2/settings-app#30]
https://github.com/rackt/react-router

**Comment by nicolayr** [comment]
The Reackt Router is now the [React Router](https://github.com/reactjs/react-router)

**Comment by adhbh** [comment]
I am adding this feature to the app. I had few doubts- 

1. Do we need it for SideBar component only?
2. Is settings-app the only frontend app which is using SideBar? SideBar is the component from D2-UI library, so is it being used(or will be used) in any other app?

**Comment by nicolayr** [comment]
This is related to managing the overall state of the settings app. Since the sidebar component is controller by the settings app, the issue is only indirectly related to the sidebar component.
