### ISSUE TITLE
Remove dependency on CDNs

### ISSUE THREAD

**Issue by Markionium** [dhis2/settings-app#33]
These fonts should be included in the apps.

https://github.com/dhis2/settings-app/blob/7c6d17b691eb6f891e54ecc7c374eec5153727d4/index.html#L6:L7

**Comment by nicolayr** [comment]
Both Material Design Icons and the Roboto font are now in [dhis-web-commons](http://bazaar.launchpad.net/~dhis2-devs-core/dhis2/trunk/revision/22010)

To use Material Design Icons:
```html
<link type="text/css" rel="stylesheet"
      href="../dhis-web-commons/material-design-icons/material-icons.css"/>
```
To use Roboto:
```html
<link type="text/css" rel="stylesheet" href="../dhis-web-commons/fonts/roboto.css"/>
```
