### ISSUE TITLE
Number validator isn't working correctly

### ISSUE THREAD

**Issue by nicolayr** [dhis2/settings-app#38]
Steps to reproduce:

1. Change the "Data analysis std dev factor" field in the "General" settings section
2. Any value gives the error "This field should be a number" and the setting isn't saved

**Comment by adhbh** [comment]
Gets fixed in this https://github.com/adhbh/d2-ui/commit/06c91db39efec57a5918b4d9af688d63755bf233

Kindly review :)

**Comment by jason-p-pickering** [comment]
Ah, i see this has already been fixed. Still seems to be present in the dev demo.

**Comment by nicolayr** [comment]
@jason-p-pickering Yes it's fixed, but I haven't deployed a new version to trunk yet. I'll probably do that later today.

**Comment by jason-p-pickering** [comment]
Also, in this case, the number should be greater than zero. Negative and zero standard deviations don't really make any sense.

**Comment by nicolayr** [comment]
Good point
