### ISSUE TITLE
Empty lists handling

### ISSUE THREAD

**Issue by larshelge** [dhis2/settings-app#39]
Display a placeholder option in lists when there are no options, saying e.g. "No options". This applies e.g. to general > infrastructure indicators + infrastructure data elements when there are no data element groups / indicator groups. It is currently confusing with a blank option in the list.

![infra](https://cloud.githubusercontent.com/assets/908206/13555554/90277c88-e3c3-11e5-9fc7-8df9fb8ee889.png)

**Comment by adhbh** [comment]
I have disabled the empty lists. Please let me know if this is acceptable

**Comment by adhbh** [comment]
@nicolayr  this fixes this issue. I have added the placeholders. https://github.com/dhis2/settings-app/pull/42

Let me know if there is something else required
