### ISSUE TITLE
Only accept positive numbers for standard deviation setting

### ISSUE THREAD

**Issue by nicolayr** [dhis2/settings-app#43]
Validators for the `factorDeviation` setting should include `positiveNumber`.
https://github.com/dhis2/settings-app/blob/master/src/settingsKeyMapping.js#L110

See also https://github.com/dhis2/d2-ui/issues/36

**Comment by adhbh** [comment]
https://github.com/dhis2/settings-app/pull/44 fixes this issue. Please merge https://github.com/dhis2/d2-ui/pull/39 before merging this request which also fixes https://github.com/dhis2/d2-ui/issues/36 in D2-UI
