### ISSUE TITLE
Separate approval level and approval workflow components

### ISSUE THREAD

**Issue by nicolayr** [dhis2/settings-app#46]
Currently both approval levels and approval workflows are handled by the `DataApprovalLevels` component. These should be split into separate sub-components.

**Comment by adhbh** [comment]
@nicolayr I will be doing this one after color-picker is fully completed. 
Please let me know if i understood correctly: 
1. Create two child components: DataApprovalLevels and DataApprovalWorkflows
2. Create a parent component : Approvals and within that I render tabs etc.
`<div style={styles.tabBody}>
            {this.state.showWorkflows ? <DataApprovalWorkflows {...someProps} /> : <DataApprovalLevels {...someOtherProps} /> }
</div>`
3. Then in app.component 
`case 'approval':
                    return Object.assign({}, fieldBase, {
                        component: Approvals,
 });`

**Comment by nicolayr** [comment]
Yes @adhbh, that's basically what I had in mind :+1:

**Comment by adhbh** [comment]
@nicolayr 
I am writing the new components as ES6 classes. React ES6 launched without mixin support: https://facebook.github.io/react/docs/reusable-components.html#no-mixins

There is a workaround: https://github.com/brigand/react-mixin This is working good for Translate mixin in DataApproveWorkflow. 
We are using mixins in other components as well we and we have to rewrite these components as ES6 classes. I think we should use this library for now?

**Comment by Markionium** [comment]
Regarding the Translate mixin. It might be useful to write this as a component as well. This could then be used for simple translations. 

Where you would normally do `<div>{this.getTranslation('somestring')}</div>`, we could then write `<Translate key="somestring" />` or perhaps even `<Translate>somestring</Translate>`.

In the cases where we would really need to supply the translation function (`this.getTranslation`) perhaps we could use a higher order component, as suggested by the author of the workaround.

I'll try to think of a clean way to do this as i need the same thing for a different application if i'd rewrite it as classes.

**Comment by adhbh** [comment]
@Markionium 
Yeah, we should replace all the mixins with higher ordered components. I will do it for Translate for now. :+1:  :) However, we can use react-mixin library for some of the mixins - like Navigation mixin from react-router which is used in Maintenance app.

**Comment by Markionium** [comment]
If it is needed yes :) The Navigation mixin for react-router is deprecated in v2 of react-router. I'm replacing it there with the alternative. We might have some other places where we would indeed need a mixin though (non come to mind right now though.)

**Comment by nicolayr** [comment]
When it comes to translation specifically, all we gain from using the mixin at the moment is typing `this.getTranslation(..)` instead of `this.context.d2.i18n.getTranslation(..)`.

In ES6 classes that can simply be done in the constructor:

```javascript
class MyComponent extends React.Component {
  constructor(props, context) {
    this.getTranslation = context.d2.i18n.getTranslation;
  }
}

MyComponent.contextTypes = {
  d2: React.PropTypes.object.isRequired
};
```

**Comment by Markionium** [comment]
Thats right, i think for the cases where we have to use it programatically that could be the (temporary) solution. It would make it pretty obvious what is going on.

**Comment by adhbh** [comment]
:+1: 
Also had to do `this.translations = context.d2.i18n.translations;` Works perfectly :dancers:

**Comment by nicolayr** [comment]
Right, that's because `getTranslation()` looks at `this.translations`, and `this` will be bound to the component class. So it would be cleaner to do:
```js
this.getTranslation = context.d2.i18n.getTranslation.bind(context.d2.i18n);
```
