### ISSUE TITLE
Move form field components to D2-UI

### ISSUE THREAD

**Issue by nicolayr** [dhis2/settings-app#48]
Currently the settings app contains the following form field components:

- `CheckBox`
- `DropDown`
- `FileUpload` (should probably be called `ImageUpload` instead)
- `MultiToggle`
- `TextField`
- `SelectFieldAsyncSource` (could be merged into `DropDown`)

These should be moved to [D2-UI](https://github.com/dhis2/d2-ui) instead.

**Comment by nicolayr** [comment]
@Markionium you probably have some similar but not identical versions of these components in the maintenance app too? Would be good to consolidate them.

**Comment by Markionium** [comment]
Agreed, we should probably do this before this stuff gets out of hand and the differences are quite large.

Perhaps it would be a good idea to combine this effort with https://github.com/dhis2/settings-app/issues/47 as that should give both apps the same api for dealing with the forms.

**Comment by nicolayr** [comment]
Yes that would be good. Although the `FormBuilder` component makes as few assumptions as possible about form fields so anything that works with `Form` _should_ work with `FormBuilder` too without changes.

Specifically, `FormBuilder` assumes that form fields:

- Take a `value` prop.
- Trigger the `onChange` event handler when the value changes.
- Pass an object like `{ target: { value: newValue } }` to the onChange event handler.

Additionally it passes `errorStyle` and `errorText` props to fields to display validation error messages.
