### ISSUE TITLE
Add icons to the menu

### ISSUE THREAD

**Issue by nicolayr** [dhis2/settings-app#57]

**Comment by Markionium** [comment]
I have already added the ability to add icons to the Sidebar component which looks for an `icon` property on the `section` object passed through the `sections` prop.

https://github.com/dhis2/d2-ui/blob/master/src/sidebar/Sidebar.component.js#L161

It can be used as follows.
https://github.com/dhis2/maintenance-app/blob/master/src/SideBar/sideBarStore.js#L21-L23

We could have a default icon... which could possibly be an empty one. To be sure that when you don't pass icons the sidebar will still look similar to the other apps. But i guess that should just be the devs responsibility.

**Comment by nicolayr** [comment]
@Markionium I'm aware of that - but because of the `FormBuilder` changes I'm not using the latest version of D2-UI in the settings app.
