### ISSUE TITLE
Add keyAnalysisDigitGroupSeparator setting key

### ISSUE THREAD

**Issue by larshelge** [dhis2/settings-app#62]
Add a new system setting for digit group separator under Appearance, next under "Property to display in analysis modules".

Key: keyAnalysisDigitGroupSeparator
Label: Default digit group separator to display in analysis modules
Options (key / label): Space / SPACE, Comma / COMMA, None / NONE

**Comment by larshelge** [comment]
Back-porting to 2.23 would be useful.

**Comment by nicolayr** [comment]
Back ported to 2.23.
