### ISSUE TITLE
Add settings to global search index

### ISSUE THREAD

**Issue by nicolayr** [dhis2/settings-app#70]
Each individual system setting should be searchable from the global app bar search field

**Comment by Markionium** [comment]
We should probably put this search index somewhere thats more globally available, perhaps the manifest. But not sure how that would work yet either.. :)

At the moment maintenance is basically a static file https://github.com/dhis2/d2-ui/tree/master/src/app-header/search/sources

So you could add it there in a similar fashion. But for the long term we should find something better.

**Comment by nicolayr** [comment]
The problem is if we make it _too_ flexible it can easily become an unworkable resource hog. Probably the best solution for third party apps would be to put it in the manifest, or even to add support in the API to allow apps to dynamically update the index.

But for internal apps the best solution might be to collect info from the apps and generate an index during  build.

**Comment by Markionium** [comment]
Agreed! Perhaps we need an api endpoint that collects those for us, and gives one single "source list" for  internal or external alike.
