### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by larshelge** [dhis2/settings-app#75]
Introduce the about page in the settings app. Add a menu item called "About". Show the about labels + values in the page.

The corresponding API resource:

<pre>/api/system/info</pre>

If a property is not present, hide both the label and the value. (Test using a user with ALL).

Note that the about values are not settings, simply static info about the DHIS 2 setup.

**Comment by nicolayr** [comment]
This will require support for deep linking (#30)

**Comment by nicolayr** [comment]
It would also be useful to include a list of all core apps and their version numbers here.
