### ISSUE TITLE
Not able to change Interface language

### ISSUE THREAD

**Issue by abyot** [dhis2/settings-app#80]
![image](https://cloud.githubusercontent.com/assets/4967749/18673017/9255f3ea-7f4a-11e6-8eeb-8b81238adc73.png)

![image](https://cloud.githubusercontent.com/assets/4967749/18673059/ad264152-7f4a-11e6-9a76-abc4fd4506a3.png)

**Comment by nicolayr** [comment]
For a little while there the settings values were encoded as JSON before transmission to the server even though the API actually expects plain strings (text/plain). In the case described here for example the settings app sent `"en"` instead of `en`. This was a bug in D2, and it has been fixed.
